#!/usr/bin/env bash
#
# Cross-platform alias installer for htj (HEIC to JPG Converter)
#
# Detects the operating system and current shell, then adds a persistent
# htj function/alias to the appropriate shell profile so you can run:
#
#   htj --input <folder> [--output <folder>]
#
# Usage:
#   ./scripts/setup.sh           (bash)
#   zsh ./scripts/setup.sh       (zsh)
#

set -euo pipefail

# -----------------------------------------------------------------------------
# Resolve the directory containing this script, supporting both bash and zsh.
# -----------------------------------------------------------------------------
SCRIPT_DIR=""
if [ -n "${BASH_SOURCE[0]:-}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [ -n "${ZSH_VERSION:-}" ]; then
    # In zsh, ${(%):-%x} expands to the current script path.
    SCRIPT_PATH="${(%):-%x}"
    SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"
else
    echo "Unsupported shell. Please run this script with bash or zsh." >&2
    exit 1
fi

PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# -----------------------------------------------------------------------------
# OS detection
# -----------------------------------------------------------------------------
OS="unknown"
case "$(uname -s)" in
    Linux*)     OS="linux";;
    Darwin*)    OS="macos";;
    CYGWIN*)    OS="windows";;
    MINGW*)     OS="windows";;
    MSYS*)      OS="windows";;
    *)          OS="unknown";;
esac

# -----------------------------------------------------------------------------
# Binary path selection
# -----------------------------------------------------------------------------
BINARY_NAME="HeicToJPG"
if [ "${OS}" = "windows" ]; then
    BINARY_NAME="HeicToJPG.exe"
fi

BINARY_PATH="${PROJECT_ROOT}/dist/${BINARY_NAME}"

# Verify the binary exists. If not, offer a helpful hint.
if [ ! -f "${BINARY_PATH}" ]; then
    echo "WARNING: Expected binary not found at: ${BINARY_PATH}"
    echo "You may need to publish for your platform first. For example:"
    echo "  dotnet publish HeicToJPG.csproj -c Release -o dist -r ${OS}-x64 --self-contained true"
    echo ""
    echo "Continuing anyway; the alias will point to that path once the binary exists."
fi

# Escape the path for safe embedding in shell code.
ESCAPED_BINARY_PATH="${BINARY_PATH//\\/\\\\}"
ESCAPED_BINARY_PATH="${ESCAPED_BINARY_PATH//\'/\\\'}"

 # -----------------------------------------------------------------------------
# Shell / profile detection
# Detect the shell actually running this script (bash, zsh, fish) rather than
# the user's login shell ($SHELL), so `zsh ./scripts/setup.sh` installs into .zshrc.
# -----------------------------------------------------------------------------
SHELL_NAME=""
if [ -n "${ZSH_VERSION:-}" ]; then
    SHELL_NAME="zsh"
elif [ -n "${BASH_VERSION:-}" ]; then
    SHELL_NAME="bash"
else
    # Fall back to the login shell.
    SHELL_NAME="${SHELL##*/}"
fi
SHELL_NAME="${SHELL_NAME:-bash}"

PROFILE_FILE=""
case "${SHELL_NAME}" in
    zsh)
        PROFILE_FILE="${HOME}/.zshrc"
        ;;
    bash)
        # Prefer .bashrc; fall back to .bash_profile if not present.
        if [ -f "${HOME}/.bashrc" ]; then
            PROFILE_FILE="${HOME}/.bashrc"
        elif [ -f "${HOME}/.bash_profile" ]; then
            PROFILE_FILE="${HOME}/.bash_profile"
        else
            PROFILE_FILE="${HOME}/.bashrc"
        fi
        ;;
    fish)
        PROFILE_FILE="${HOME}/.config/fish/config.fish"
        mkdir -p "$(dirname "${PROFILE_FILE}")"
        ;;
    *)
        PROFILE_FILE="${HOME}/.profile"
        ;;
esac

# -----------------------------------------------------------------------------
# Profile snippet generation (idempotent)
# -----------------------------------------------------------------------------
MARKER="# htj alias generated by homebrew-htj/scripts/setup.sh"

add_bash_zsh_snippet() {
    cat >> "${PROFILE_FILE}" <<EOF

${MARKER}
htj() {
    "${ESCAPED_BINARY_PATH}" "\$@"
}
EOF
}

add_fish_snippet() {
    cat >> "${PROFILE_FILE}" <<EOF

${MARKER}
function htj
    "${ESCAPED_BINARY_PATH}" \$argv
end
EOF
}

# Check whether the profile already contains our marker to avoid duplicates.
if [ -f "${PROFILE_FILE}" ] && grep -qF "${MARKER}" "${PROFILE_FILE}"; then
    echo "htj alias already installed in ${PROFILE_FILE}"
    echo "Reload your shell or run: source ${PROFILE_FILE}"
    exit 0
fi

# Append the snippet.
mkdir -p "$(dirname "${PROFILE_FILE}")"
case "${SHELL_NAME}" in
    fish)
        add_fish_snippet
        ;;
    *)
        add_bash_zsh_snippet
        ;;
esac

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------
echo "Detected OS: ${OS}"
echo "Detected shell: ${SHELL_NAME}"
echo "Added htj alias to ${PROFILE_FILE}"
echo "Binary path: ${BINARY_PATH}"
echo ""
echo "Reload your shell or run:"
echo "  source ${PROFILE_FILE}"
echo ""
echo "Then use it like:"
echo "  htj --input /path/to/heic-folder --output /path/to/jpg-folder"
