#
# Windows PowerShell alias installer for htj (HEIC to JPG Converter)
#
# Adds a persistent htj function to the current user's PowerShell profile so
# you can run:
#
#   htj --input <folder> [--output <folder>]
#
# Usage:
#   .\scripts\setup.ps1
#

$ErrorActionPreference = "Stop"

# Resolve project root from script location.
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ProjectRoot = Resolve-Path (Join-Path $ScriptDir "..")
$BinaryPath = Join-Path $ProjectRoot "dist\HeicToJPG.exe"

# Ensure a PowerShell profile exists.
if (-not (Test-Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
}

# Verify the binary exists. If not, offer a helpful hint.
if (-not (Test-Path $BinaryPath)) {
    Write-Warning "Expected binary not found at: $BinaryPath"
    Write-Host "You may need to publish for Windows first. For example:" -ForegroundColor Yellow
    Write-Host "  dotnet publish HeicToJPG.csproj -c Release -o dist -r win-x64 --self-contained true"
    Write-Host ""
    Write-Host "Continuing anyway; the alias will point to that path once the binary exists."
}

# Idempotency marker.
$Marker = "# htj function generated by homebrew-htj/scripts/setup.ps1"

$Snippet = @"

$Marker
function htj {
    & "$BinaryPath" @args
}
"@

$ProfileContent = Get-Content -Path $PROFILE -Raw -ErrorAction SilentlyContinue

if ($ProfileContent -and $ProfileContent.Contains($Marker)) {
    Write-Host "htj function already installed in $PROFILE"
    Write-Host "Reload PowerShell or run: . `$PROFILE"
    exit 0
}

Add-Content -Path $PROFILE -Value $Snippet

Write-Host "Detected shell: PowerShell" -ForegroundColor Green
Write-Host "Added htj function to $PROFILE" -ForegroundColor Green
Write-Host "Binary path: $BinaryPath"
Write-Host ""
Write-Host "Reload PowerShell or run:"
Write-Host "  . `$PROFILE"
Write-Host ""
Write-Host "Then use it like:"
Write-Host "  htj --input C:\path\to\heic-folder --output C:\path\to\jpg-folder"
